- hosts: all
  become: true
  tasks:
    - name: Copy files from Ansible server
      copy:
        src: /home/pipebox/playbooks
        dest: /home/ubuntu/ymlfiles/
      become: true

    - name: Delete old deployment
      command: kubectl delete -f /home/ubuntu/ymlfiles/Deployment.yml
      become: true

    - name: Delete old service
      command: kubectl delete -f /home/ubuntu/ymlfiles/Service.yml
      become: true

    - name: Pull Docker image from DockerHub
      command: docker pull goldenkiwi1324/web-pipe-line:latest
      ignore_errors: true

    - name: Create new deployment
      command: kubectl apply -f /home/ubuntu/ymlfiles/Deployment.yml
      become: true

    - name: Create new service
      command: kubectl apply -f /home/ubuntu/ymlfiles/Service.yml
      become: true
