- hosts: all
  become: true
  tasks: 
     - name: create new deployment
       command: kubectl apply -f /home/playbooks/Deployment.yml
     - name: create new service
       command: kubectl apply -f /home/playbooks/Service.yml
 
