- hosts: all
  become: true
  tasks:


    - name: Copy files from Ansible server
      copy:
        src: /home/pipebox/playbooks
        dest: /home/ubuntu/ymlfiles/
      become: true
      
    - name: Delete old deployment
      command: kubectl delete -f /home/ubuntu/ymlfiles/Deployment.yml
      ignore_errors: true

    - name: Delete old service
      command: kubectl delete -f /home/ubuntu/ymlfiles/Service.yml
      ignore_errors: true

    - name: Pull Docker image from DockerHub
      command: docker pull goldenkiwi1324/web-pipe-line:latest
      ignore_errors: true

    - name: Create new deployment
      command: kubectl apply -f /home/ubuntu/ymlfiles/Deployment.yml

    - name: Create new service
      command: kubectl apply -f /home/ubuntu/ymlfiles/Service.yml

    - name: Get pod names
      shell: kubectl get pods -l app=mariadb -o jsonpath='{.items[*].metadata.name}'
      register: pod_names

    - name: Rename pods
      shell: |
        i=1
        for pod in {{ pod_names.stdout | from_json | join(' ') }}; do
          new_name="deployment-$i"
          kubectl rename pod "$pod" "$new_name"
          ((i=i+1))
        done
