apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: webapp
  template:
    metadata:
      labels:
        app: webapp
    spec:
      containers:
      - name: webapp
        image: goldenkiwi1324/web-pipe-line:latest
        ports:
        - containerPort: 5000
      - name: mariadb
        image: mariadb
        env:
          - name: MYSQL_ROOT_PASSWORD
            value: zldnl88
          - name: MYSQL_DATABASE
            value: flector
        ports:
        - containerPort: 3306
