---
- name: Execute commands on Kubernetes Pod
  hosts: localhost
  gather_facts: no
  tasks:
    - name: Run command 1 - kubectl exec to get a shell inside the mariadb container
      command: kubectl exec -it deployment-547f7c9c89-bjq8f -c mariadb /bin/bash
      args:
        stdin: yes
        stdin_add_newline: yes
        prompt: "root@deployment-547f7c9c89-bjq8f:/$"

    - name: Run command 2 - mariadb -u root -p
      command: mariadb -u root -p
      args:
        stdin: yes
        stdin_add_newline: yes
        prompt: "Enter password: "

    - name: Run command 3 - zldnl88
      command: zldnl88
      args:
        stdin: yes
        stdin_add_newline: yes
        prompt: "MariaDB [(none)]> "

    - name: Run command 4 - USE flector;
      command: USE flector;
      args:
        stdin: yes
        stdin_add_newline: yes
        prompt: "Database changed"

    - name: Run command 5 - CREATE TABLE flower ...
      command: >
        mariadb -u root -p -e "CREATE TABLE flower (
          id INT AUTO_INCREMENT PRIMARY KEY,
          name VARCHAR(255),
          word VARCHAR(255),
          etc VARCHAR(255),
          modelnum INT
        );"
      args:
        stdin: yes
        stdin_add_newline: yes
        prompt: "MariaDB [(none)]> "

    - name: Run command 6 - CREATE TABLE song ...
      command: >
        mariadb -u root -p -e "CREATE TABLE song (
          id INT AUTO_INCREMENT PRIMARY KEY,
          title VARCHAR(255),
          artist VARCHAR(255),
          genre VARCHAR(255),
          rdate VARCHAR(255),
          lyrics VARCHAR(255),
          enlyr VARCHAR(255),
          preproc VARCHAR(255),
          postproc VARCHAR(255)
        );"
      args:
        stdin: yes
        stdin_add_newline: yes
        prompt: "MariaDB [(none)]> "

    - name: Run command 7 - exit from mariadb shell
      command: exit
      args:
        stdin: yes
        stdin_add_newline: yes
        prompt: "root@deployment-547f7c9c89-bjq8f:/$"

    - name: Run command 8 - exit from the Kubernetes Pod shell
      command: exit
      args:
        stdin: yes
        stdin_add_newline: yes
        prompt: "root@deployment-547f7c9c89-bjq8f:/$"
